### ISSUE TITLE
question | what is the matcher_patterns.json file ?

### ISSUE THREAD

**Issue by zzzjl2021** [Anni-Zou/Decker#1]
Dear authers:
Thanks for sharing code~
A confusion about understanding the code:
In the data_preprocess-grounded.py, what is the exact content of the matcher_patterns? 

PATTERN_PATH = '../data/cpnet/matcher_patterns.json'

I have read the download_rawdata_resources.sh , while it doesn't have any clues about this file.
The paper doesn't provide details about this operation too.

**Comment by yzc111** [comment]
have find this file? I think it is in conceptnet

**Comment by zhxfei** [comment]
I have same problem, and i think you can try to process raw data as same as project [qagnn](https://github.com/michiyasunaga/qagnn).

**Comment by Wepdekr** [comment]
I had the same problem, may I ask how you solved it in the end?

**Comment by Anni-Zou** [comment]
Thanks for your attention. The file  `._./data/cpnet/matcher_patterns.json'_` is downloaded simultaneously with the ConceptNet. You will find this file in `/data/cpnet` if you run the script in `download_rawdatat_resources.sh`.
