### ISSUE TITLE
I can not find the definiton of the class MyConFact_RGCN.

### ISSUE THREAD

**Issue by zhxfei** [Anni-Zou/Decker#4]
The code you published seems without the defintion of class MyConFact_RGCN which is the most import component of your work.

Decker/run_confact.py", line 39, in <module>
    from model.modeling_v3 import MyConFact_RGCN
ImportError: cannot import name 'MyConFact_RGCN' from 'model.modeling_v3' (/data/home/zhuxiaofei/Decker/model/modeling_v3.py)

**Comment by Anni-Zou** [comment]
Thanks for your attention. We have updated the file now.

**Comment by zhxfei** [comment]
There are no file dataset.py which used in Decker/run_confact.py.

from dataset import MyDataset, Split
