### ISSUE TITLE
I can't find the module 'dataset' in this code

### ISSUE THREAD

**Issue by Wepdekr** [Anni-Zou/Decker#5]
In 'run_confact.py', line 40, in
from dataset import MyDataset, Split

But the code you published seems without the module dataset.

Traceback (most recent call last):
  File "/root/autodl-tmp/Decker-main/run_confact.py", line 40, in <module>
    from dataset import MyDataset, Split
ModuleNotFoundError: No module named 'dataset'

**Comment by Anni-Zou** [comment]
Hello, relevant files have been updated.
